spring:
  redis:
    database: 0
    host: local_server
    port: 6379
    timeout: PT30S
    connect-timeout: PT20S
  datasource:
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:p6spy:mysql://local_server:3306/zy_fk_core?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&allowMultiQueries=true&zeroDateTimeBehavior=convertToNull
    username: root
    password: P@ssw0rd
    connection-init-sqls: set names utf8mb4;